export type LandingPage = {
  path: string;
  kind: "service" | "market";
  title: string;
  eyebrow: string;
  intro: string;
  service: string;
  market: string;
  overviewTitle: string;
  overview: string[];
  process: { title: string; text: string }[];
  proof: string[];
  faqs: { question: string; answer: string }[];
  resources: { label: string; href: string; external?: boolean }[];
  related: { label: string; href: string }[];
};

export const landingPages: LandingPage[] = [
  {
    path: "/services/permit-expediting", kind: "service", title: "Permit Expediting Services", eyebrow: "Application-to-issuance coordination",
    intro: "Organized permit coordination for contractors, owners, and design teams that need clear status, accountable follow-up, and fewer preventable submission problems.",
    service: "permit-general", market: "", overviewTitle: "A managed path through permit review",
    overview: ["Permit expediting is not a promise to bypass public review. It is disciplined management of the information, deadlines, contacts, and corrections that move an application through its required steps.", "Team K5 reviews the administrative readiness of a package, tracks the jurisdiction’s published process, organizes reviewer comments, and keeps the project team focused on the next required action."],
    process: [{title:"Scope and jurisdiction intake",text:"We identify the project address, work type, applicant roles, target jurisdiction, and known schedule constraints."},{title:"Submission readiness review",text:"We organize required forms and supporting files, flag visible gaps, and confirm who must answer technical design questions."},{title:"Tracking and response control",text:"We monitor available status channels, maintain an action list, and coordinate complete responses to review comments."},{title:"Issuance handoff",text:"We confirm outstanding administrative conditions and deliver a clear record of permit status and next steps."}],
    proof:["Founded in 2003 by a former building official and inspector.","A defined workflow separates administrative coordination from decisions reserved for licensed designers, contractors, and public officials.","Project intake captures the municipality, scope, and timeline before work is proposed."],
    faqs:[{question:"Can an expediter guarantee approval or a review date?",answer:"No. The authority having jurisdiction controls review, approval, fees, and inspections. Good coordination reduces avoidable friction but does not replace public review."},{question:"When should Team K5 become involved?",answer:"Early involvement is useful when the jurisdiction and project scope are known, but we can also organize an application already in review."},{question:"Who answers technical plan comments?",answer:"The responsible architect, engineer, contractor, or other qualified project professional answers technical comments. We coordinate the response workflow and records."}],
    resources:[{label:"Florida permit submittal checklist",href:"/blog/florida-permit-submittal-checklist"},{label:"How to respond to review comments",href:"/blog/responding-to-florida-permit-review-comments"}],
    related:[{label:"Commercial permit expediting",href:"/services/commercial-permit-expediting"},{label:"Residential permit expediting",href:"/services/residential-permit-expediting"},{label:"Florida permit expediting",href:"/markets/florida-permit-expediting"}]
  },
  {
    path:"/services/commercial-permit-expediting",kind:"service",title:"Commercial Permit Expediting",eyebrow:"Coordination for tenant improvements and commercial construction",intro:"Keep multi-discipline commercial submissions, reviewer comments, and stakeholder decisions moving in one controlled workflow.",service:"permit-commercial",market:"",overviewTitle:"Commercial review requires active coordination",
    overview:["Commercial applications commonly involve several plan disciplines and separate reviews for building, fire, zoning, utilities, or other local requirements. A delay in one response can hold the larger package.", "Team K5 creates a shared action record so owners, contractors, and design professionals can see what is pending, who owns it, and what must return to the jurisdiction."],
    process:[{title:"Requirements map",text:"Document the proposed use, scope, jurisdiction, project contacts, and known prerequisite reviews."},{title:"Package control",text:"Check naming, forms, signatures, and document organization before submission through the jurisdiction’s accepted channel."},{title:"Review coordination",text:"Sort comments by discipline and responsible party, then track coordinated resubmission files."},{title:"Closeout to issuance",text:"Track administrative holds, fees, and final issuance conditions reported by the jurisdiction."}],
    proof:["Experience is presented as process knowledge, not a claim of influence over reviewers.","Status reporting gives the project team an auditable list of open actions.","Suitable for one location or a repeat commercial rollout."],
    faqs:[{question:"Do you prepare architectural or engineering revisions?",answer:"No. Licensed design professionals remain responsible for technical documents. We organize and track their responses."},{question:"Can you coordinate prerequisite approvals?",answer:"We can track identified prerequisite steps and responsible contacts; the exact sequence depends on the jurisdiction and project."},{question:"Is this only for large projects?",answer:"No. Tenant improvements and smaller commercial scopes can benefit when schedule, multiple disciplines, or owner reporting make coordination important."}],
    resources:[{label:"Permit review comment guide",href:"/blog/responding-to-florida-permit-review-comments"}],related:[{label:"Multi-site permit coordination",href:"/services/multi-site-permit-coordination"},{label:"Inspection scheduling",href:"/services/inspection-scheduling"},{label:"Tampa permit expediting",href:"/markets/tampa-permit-expediting"}]
  },
  {
    path:"/services/residential-permit-expediting",kind:"service",title:"Residential Permit Expediting",eyebrow:"Clear coordination for residential improvements and construction",intro:"Organize residential permit paperwork, status, and corrections without leaving homeowners or contractors guessing about the next step.",service:"permit-residential",market:"",overviewTitle:"A practical workflow for residential permits",
    overview:["Residential scopes vary widely—from alterations and equipment replacements to additions and new construction. The required documents depend on the work and the reviewing jurisdiction.", "We begin with the actual address and scope, then help the project team manage administrative requirements and reviewer responses. We do not substitute generic checklists for jurisdiction instructions."],
    process:[{title:"Address and scope review",text:"Confirm property jurisdiction, proposed work, contractor and owner roles, and available plans."},{title:"Document checklist",text:"Organize forms and supporting records around the jurisdiction’s current published requirements."},{title:"Application monitoring",text:"Track available status and translate administrative next steps into a clear task list."},{title:"Correction coordination",text:"Route comments to the right project professional and keep revised files together for resubmission."}],
    proof:["Every engagement starts with an address and project scope.","Homeowners receive plain-language status while licensed parties retain their technical responsibilities.","No promise of approval, special access, or shortened government review."],
    faqs:[{question:"Can a homeowner hire Team K5 directly?",answer:"Yes. Intake still needs the contractor and design contacts when their participation is required."},{question:"Will you determine whether my work needs a permit?",answer:"The applicable jurisdiction makes that determination. We can help identify the jurisdiction and locate its published guidance."},{question:"Do you schedule inspections after issuance?",answer:"Inspection coordination is available as a related service when the permit and site are ready."}],
    resources:[{label:"Florida submittal checklist",href:"/blog/florida-permit-submittal-checklist"}],related:[{label:"Permit expediting overview",href:"/services/permit-expediting"},{label:"Inspection scheduling",href:"/services/inspection-scheduling"},{label:"Orlando permit expediting",href:"/markets/orlando-permit-expediting"}]
  },
  {
    path:"/services/inspection-scheduling",kind:"service",title:"Construction Inspection Scheduling",eyebrow:"Permit inspection coordination",intro:"Coordinate inspection requests, site contacts, prerequisites, and results so the field team has a reliable next-action record.",service:"inspection",market:"",overviewTitle:"Scheduling is more than placing a request",
    overview:["An inspection request is useful only when the correct inspection is eligible, the site is ready, and the jurisdiction has the information it requires. Team K5 coordinates those administrative details with the permit holder and field team.", "Inspection availability and results always remain with the authority having jurisdiction. We track requests and outcomes rather than promising a particular time or result."],
    process:[{title:"Permit readiness",text:"Confirm permit identifiers, inspection type, prerequisites, and the authorized requesting party."},{title:"Site coordination",text:"Collect access details and the correct field contact before using the jurisdiction’s accepted request method."},{title:"Request tracking",text:"Record confirmation details and communicate the jurisdiction-provided schedule or window."},{title:"Result follow-up",text:"Capture posted results and coordinate the next request or corrective action with the project team."}],
    proof:["Requests are tied to permit records and an identified site contact.","Results and failed-item notes are documented without rewriting an inspector’s direction.","Coordination supports residential, commercial, and multi-location work."],
    faqs:[{question:"Can you guarantee a next-day inspection?",answer:"No. Cutoff times and availability are controlled by each jurisdiction."},{question:"Who must make the site ready?",answer:"The permit holder and field team are responsible for readiness, access, and required documents. We coordinate the request information."},{question:"What happens after a failed inspection?",answer:"We record the posted result and help route the issue to the responsible contractor or professional before a reinspection is requested."}],
    resources:[{label:"Contact project intake",href:"/contact?service=inspection"}],related:[{label:"Commercial permit expediting",href:"/services/commercial-permit-expediting"},{label:"Multi-site coordination",href:"/services/multi-site-permit-coordination"}]
  },
  {
    path:"/services/e-recording-notice-of-commencement",kind:"service",title:"E-Recording & Notice of Commencement Service",eyebrow:"Florida construction document coordination",intro:"Prepare the recording workflow for Notices of Commencement and related construction records with careful attention to county and project requirements.",service:"erecording",market:"",overviewTitle:"Connect recording to the permit workflow",
    overview:["In Florida, a Notice of Commencement is a statutory construction document that may be required in connection with permitting and inspections. Requirements, recording acceptance, and posting practices must be confirmed for the project and county.", "Team K5 coordinates document intake, recording submission through accepted channels, and return of the recorded instrument. We do not provide legal advice or decide whether a notice is legally required."],
    process:[{title:"Project and county intake",text:"Collect property, owner, contractor, lender, and other information required for the project’s document workflow."},{title:"Execution check",text:"Confirm the document is complete for submission and identify signature, witness, or notarization steps without offering legal conclusions."},{title:"Recording submission",text:"Submit through an available accepted recording channel and track rejection or acceptance messages."},{title:"Recorded copy delivery",text:"Return the recorded instrument and help connect it to the permit or inspection record as directed."}],
    proof:["The service distinguishes recording coordination from legal advice.","County recording and jurisdiction permit systems are treated as separate official processes.","Recorded copies and submission outcomes are retained in the project workflow."],
    faqs:[{question:"Does Team K5 provide legal advice about lien law?",answer:"No. Consult a Florida attorney for legal interpretation or rights under Chapter 713."},{question:"Does recording automatically update the permit?",answer:"Not always. The recorded document may need to be supplied to the permitting jurisdiction using its required process."},{question:"Can you notarize the document?",answer:"Ask during intake about current notary coordination options and the requirements for the signer and document."}],
    resources:[{label:"Florida Notice of Commencement guide",href:"/blog/florida-notice-of-commencement-permitting"},{label:"Florida Statutes Chapter 713",href:"https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0700-0799/0713/0713.html",external:true}],related:[{label:"Permit expediting",href:"/services/permit-expediting"},{label:"Palm Beach permit expediting",href:"/markets/palm-beach-permit-expediting"}]
  },
  {
    path:"/services/multi-site-permit-coordination",kind:"service",title:"Multi-Site Permit Coordination",eyebrow:"Portfolio and rollout permit management",intro:"Give program leaders one accountable view of permit progress across locations, jurisdictions, vendors, and opening schedules.",service:"multi-site",market:"other-national",overviewTitle:"Standardize the workflow, not the jurisdiction",
    overview:["A repeat scope does not create a repeat permit process. Each location can have different forms, portals, prerequisite reviews, and responsible contacts.", "Team K5 uses a consistent portfolio reporting structure while maintaining location-specific requirements. That balance lets leaders compare progress without hiding local differences."],
    process:[{title:"Portfolio setup",text:"Define sites, target dates, scope families, stakeholders, and reporting expectations."},{title:"Jurisdiction matrix",text:"Record the authority, submission channel, known requirements, and dependencies for each address."},{title:"Site execution",text:"Coordinate package readiness, submissions, comments, fees, and issuance actions by location."},{title:"Program reporting",text:"Provide consistent status categories, risks, owners, and next actions across the rollout."}],
    proof:["Location-level records prevent a national template from overriding local instructions.","Exception reporting highlights sites needing project-team decisions.","Team K5 supports Florida, Southeast, and national coordination without claiming local offices everywhere."],
    faqs:[{question:"How many sites qualify as a multi-site program?",answer:"There is no fixed minimum. The model is useful when shared reporting and repeat workflows reduce coordination burden."},{question:"Can every location use the same package?",answer:"Usually not without adjustments. The design team establishes the technical prototype while each jurisdiction’s requirements are tracked separately."},{question:"Can you work with our existing vendors?",answer:"Yes. Intake can define roles for architects, engineers, contractors, landlords, and internal program managers."}],
    resources:[{label:"Start portfolio intake",href:"/contact?service=multi-site&market=other-national"}],related:[{label:"Commercial permit expediting",href:"/services/commercial-permit-expediting"},{label:"Florida permit expediting",href:"/markets/florida-permit-expediting"}]
  },
  {
    path:"/markets/florida-permit-expediting",kind:"market",title:"Florida Permit Expediting",eyebrow:"Statewide permit and document coordination",intro:"Coordinate Florida permit applications without treating hundreds of local authorities as one uniform system.",service:"permit-general",market:"other-national",overviewTitle:"Florida rules meet local administration",
    overview:["The Florida Building Code provides a statewide framework, but permits are administered by local authorities having jurisdiction. Forms, digital portals, zoning reviews, fees, and document routing vary by address and scope.", "Our Florida workflow starts by identifying the correct authority and its current instructions. We then coordinate the administrative record while project professionals remain responsible for code analysis and technical design."],
    process:[{title:"Identify the authority",text:"Verify the project address and whether a city, county, or other agency administers the permit."},{title:"Map local requirements",text:"Use current official guidance to document submission channels and administrative prerequisites."},{title:"Coordinate review",text:"Track local status, comments, and responsible project-team responses."},{title:"Connect downstream steps",text:"Organize issuance, Notice of Commencement, and inspection actions applicable to the project."}],
    proof:["Florida service areas are accurately labeled as service areas, not staffed offices.","Local requirements are checked by address instead of inferred from a city name.","Team K5 was founded by a former Florida building official and inspector in 2003."],
    faqs:[{question:"Is there one statewide permit portal?",answer:"No. Florida permitting is generally administered by local authorities, each with its own processes."},{question:"Do you serve projects outside your three listed Florida service areas?",answer:"Yes, project coordination may be available statewide. The listed Clermont, Brandon, and Lake Worth areas are service areas, not claims of offices."},{question:"Does the Florida Building Code determine zoning approval?",answer:"Zoning and land-use administration are separate local functions and may be part of the project’s prerequisites."}],
    resources:[{label:"Florida Building Commission",href:"https://floridabuilding.org/",external:true},{label:"Florida permit checklist",href:"/blog/florida-permit-submittal-checklist"}],related:[{label:"Orlando market",href:"/markets/orlando-permit-expediting"},{label:"Tampa market",href:"/markets/tampa-permit-expediting"},{label:"Palm Beach market",href:"/markets/palm-beach-permit-expediting"}]
  },
  {
    path:"/markets/orlando-permit-expediting",kind:"market",title:"Orlando Permit Expediting",eyebrow:"City of Orlando and Orange County project coordination",intro:"Start Central Florida permitting with the project address—because an Orlando mailing address does not by itself identify the permitting authority.",service:"permit-general",market:"clermont-central-florida",overviewTitle:"The first Orlando question is jurisdiction",
    overview:["Projects associated with Orlando may be inside the City of Orlando or in unincorporated Orange County. Those authorities publish separate permitting resources and use their own application systems.", "Team K5’s Central Florida service area includes Clermont. It is a service area, not represented as a staffed Orlando office. We verify the authority before building the submission and tracking plan."],
    process:[{title:"Address verification",text:"Confirm whether the parcel is administered by the City of Orlando, Orange County, or another municipality."},{title:"Agency-specific setup",text:"Follow the correct authority’s published building, zoning, and digital submission instructions."},{title:"Review action log",text:"Separate comments and holds by department and route them to the responsible party."},{title:"Permit-to-field handoff",text:"Coordinate issuance records, required recorded documents, and inspection scheduling steps."}],
    proof:["City and county resources are linked separately below.","The page makes no claim of an Orlando office or guaranteed local access.","Central Florida intake records the exact project jurisdiction."],
    faqs:[{question:"Is Orange County the permit authority for every Orlando address?",answer:"No. City limits and mailing addresses do not always align; verify the parcel and authority."},{question:"Does Team K5 have an Orlando office?",answer:"This page describes service coverage. Team K5’s listed Central Florida service area is Clermont and is not presented as a staffed office."},{question:"Can you coordinate both building and zoning review?",answer:"We can track identified administrative reviews and responsible contacts; public agencies and qualified project professionals make the underlying decisions."}],
    resources:[{label:"City of Orlando permitting services",href:"https://www.orlando.gov/Building-Development",external:true},{label:"Orange County Fast Track",href:"https://fasttrack.ocfl.net/",external:true}],related:[{label:"Residential expediting",href:"/services/residential-permit-expediting"},{label:"Florida permit expediting",href:"/markets/florida-permit-expediting"}]
  },
  {
    path:"/markets/tampa-permit-expediting",kind:"market",title:"Tampa Permit Expediting",eyebrow:"Tampa Bay permit coordination",intro:"Coordinate Tampa Bay applications by matching each address to the City of Tampa, Hillsborough County, or another local authority before submission.",service:"permit-general",market:"brandon-tampa-bay",overviewTitle:"Tampa Bay is a multi-jurisdiction market",
    overview:["A Tampa postal address can fall under different local authorities. The City of Tampa and Hillsborough County maintain separate development and permit resources, and surrounding municipalities may administer their own processes.", "Team K5’s Brandon / Tampa Bay service area is accurately described as service coverage, not a staffed Tampa office. Intake begins with the address and project scope."],
    process:[{title:"Jurisdiction confirmation",text:"Use the project address to identify the governing building and development authority."},{title:"Portal and prerequisite map",text:"Record the correct submission system and known agency reviews for the scope."},{title:"Comment coordination",text:"Maintain discipline-specific ownership for plan comments and revised documents."},{title:"Issuance and inspections",text:"Track reported conditions, permit issuance, and the authority’s inspection-request workflow."}],
    proof:["Official City of Tampa and Hillsborough County resources are distinguished.","No claim is made that Team K5 controls agency schedules or outcomes.","The Brandon / Tampa Bay location is labeled as a service area."],
    faqs:[{question:"Are City of Tampa and Hillsborough County permits interchangeable?",answer:"No. They are separate authorities with separate processes."},{question:"Do you have a staffed Tampa office?",answer:"No office claim is made. Brandon / Tampa Bay is a Team K5 service area."},{question:"Can you guarantee a permit review timeline?",answer:"No. The reviewing authority controls schedules. We provide tracking, follow-up, and action ownership."}],
    resources:[{label:"City of Tampa Construction Services",href:"https://www.tampa.gov/construction-services",external:true},{label:"Hillsborough County Development Services",href:"https://hcfl.gov/businesses/development-services",external:true}],related:[{label:"Commercial expediting",href:"/services/commercial-permit-expediting"},{label:"Inspection scheduling",href:"/services/inspection-scheduling"}]
  },
  {
    path:"/markets/palm-beach-permit-expediting",kind:"market",title:"Palm Beach County Permit Expediting",eyebrow:"Palm Beach County and municipal permit coordination",intro:"Navigate South Florida permitting by identifying whether Palm Beach County or one of its municipalities administers the project address.",service:"permit-general",market:"lake-worth-south-florida",overviewTitle:"County and municipal processes must stay distinct",
    overview:["Palm Beach County includes many incorporated municipalities, and permit administration depends on the property location. A project in the region should not be routed to a county process solely because the county appears in the mailing address.", "Team K5’s Lake Worth / South Florida service area is service coverage, not a claim of a staffed Palm Beach office. We use the project address and official agency guidance to establish the workflow."],
    process:[{title:"Property and authority check",text:"Confirm the parcel location and responsible city or county building department."},{title:"Local intake plan",text:"Document forms, submission channels, related reviews, and project-team responsibilities."},{title:"Review tracking",text:"Monitor available agency status and coordinate complete responses without blending separate authorities."},{title:"Recording and field steps",text:"Connect applicable Notice of Commencement, issuance, and inspection actions to the correct permit record."}],
    proof:["Palm Beach County and local municipal administration are not conflated.","Lake Worth / South Florida is clearly labeled as a service area.","Official county resources and Florida statutory information are provided for verification."],
    faqs:[{question:"Does Palm Beach County issue permits inside every municipality?",answer:"No. Many incorporated municipalities administer their own permits; the property authority must be confirmed."},{question:"Is Lake Worth a staffed Team K5 office?",answer:"The site identifies Lake Worth / South Florida as a service area and does not present a staffed office address."},{question:"Can Team K5 coordinate a Notice of Commencement?",answer:"Yes, recording coordination is available, subject to project and county requirements. We do not provide legal advice."}],
    resources:[{label:"Palm Beach County Planning, Zoning & Building",href:"https://discover.pbcgov.org/pzb/Pages/default.aspx",external:true},{label:"Notice of Commencement guide",href:"/blog/florida-notice-of-commencement-permitting"}],related:[{label:"E-recording and NOC",href:"/services/e-recording-notice-of-commencement"},{label:"Florida permit expediting",href:"/markets/florida-permit-expediting"}]
  }
];

export const landingPageByPath = new Map(landingPages.map(page => [page.path, page]));